### ISSUE TITLE
multipleSeparator change

### ISSUE THREAD

**Issue by lestatcheb** [millioner/django-ajax-select#2]
Can we change setting  'multipleSeparator: " "' in  templates/autocompleteselectmultiple.html without copying django_ajax_select to our project directory?

Problem is with that multipleSeparator django_ajax_select don't correct autocomplete words with spaces like "beautiful life".
instead of objects names with starts "beautiful life..." it's listing objects names starts with "life..."

Now I just copying django_ajax_select to our project and modifying multipleSeparator to ";" instead " ".

Thanks!

Sorry for my bad English.

---

UPDATE:

Seems with multipleSeparator "," has some bugs, I checked it with russian phrase "здоровый образ жизни",
django_ajax_select after part of this phrase select other phrase.

with multipleSeparator ";" it's full works.

Thanks.

---

**Comment by millioner** [comment]
I think you are right. 
It's changed to 'multipleSeparator: ","' now.
Thank you for reporting about that.

**Comment by lestatcheb** [comment]
Seems with multipleSeparator "," has some bugs, I checked it with russian phrase "здоровый образ жизни",
django_ajax_select after part of this phrase select other phrase.

with multipleSeparator ";" it's full works.

Thanks.
